export const textStyles={

    NavHead:{
        fontSize:"17px",
        fontWeight:"700",
        backgroundColor:"#14276e",
        color:"white",
        
    },
    NavText:{
        fontSize:"15px",
         fontWeight:"400",
         backgroundColor:"#14276e",
        color:"white",
    },
    NavButton:{
        fontSize:"14px",
         fontWeight:"600"

    },
    BrandPromise:{
        fontSize:"14px",
        fontWeight:"700",
        lineHeight:"14px"
    },
    BrandPromiseSmall:{
        fontSize:"10px",
        fontWeight:"400",
        lineHeight:"12px"
    },
    Filter:{
        fontSize:"20px",
        fontWeight:"600",
        lineHeight:"12px",
        padding:"20px",
        color:"black",
    
    },
    SideBarHead:{
        fontSize:"14px",
        fontWeight:"500",
        paddingBottom:"5px",
        color:"#5A5A59",
        textAlign:"initial"

    },
    SideBarText:{
        fontSize:"14px",
        fontWeight:"400",
        paddingBottom:"5px",
        color:"#333333",
        textAlign:"initial"
    },
    MainBarHead:{
        fontSize:"24px",
        fontWeight:"600",
        paddingBottom:"5px",
        color:"#333333",
        textAlign:"initial"
    },
    price:{
        fontSize:"14px",
        fontWeight:"600",
        color:"#14276e"

    },
    striked:{
        fontSize:"14px",
        fontWeight:"400",
        color:"grey",
    
    },
    SinglePageHead:{
        fontSize:"17px",
        fontWeight:"600",
        lineHeight:"15px",
        textAlign:"initial"
    },
    SinglePagePrice:{
        fontSize:"30px",
        fontWeight:"600",
        paddingBottom:"5px",
        color:"#14276e",
        textAlign:"initial"
    },
   AddToCart:{
      padding:"20px",
      paddingLeft:"10px",
      paddingRight:"10px",
      fontSize:"24px",
      backgroundColor:"Red",
      lineHeight:"15px",
      color:"white",
      margin:"20px",
      borderRadius:"0px"
   },
   BuyNow:{
    padding:"20px",
    paddingLeft:"10px",
    paddingRight:"10px",
    fontSize:"28px",
    backgroundColor:"#fc6027",
    lineHeight:"15px",
    color:"white",
    margin:"20px",
    borderRadius:"0px"
 },
 Checkout:{
   
    fontSize:"24px",
    backgroundColor:"Red",
    lineHeight:"15px",
    color:"white",
    borderRadius:"0px"
 },
 Admin:{
    fontSize:"24px",
    lineHeight:"15px",
    backgroundColor:"white",
    color:"black"
 }

};

export const styles={
    color:{
        bg:"green",
        color:"white"
    }
}